version: '3'

services:
  backend_app:
    container_name: backend_app
    build:
      context: .
    ports:
      - "9000:9000"
    restart: unless-stopped
    depends_on:
      - mysqldb
    networks:
      - infrastructure

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234XYZ
      MYSQL_DATABASE: employe_claim
      MYSQL_USER: zakir
      MYSQL_PASSWORD: zakir123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - infrastructure

networks:
  infrastructure:
    driver: bridge

volumes:
  mysql_data: